import { z } from "zod";
import { buildAiInputSnapshot } from "./snapshot";
import type { AiJobDispatcher } from "@/lib/queue/ai-job-dispatcher";
const schema=z.object({propertyId:z.string().min(1),expectedVersion:z.number().int().positive(),agentText:z.string(),mediaIds:z.array(z.string()).max(10),tasks:z.array(z.enum(["extraction","vision","content"])).min(1),idempotencyKey:z.string().min(1).max(200)}).strict();
type Context={userId:string;tenantId:string;agentProfileId:string};
type PropertyRow=Record<string,unknown>&{id:string;tenantId:string;version:number};
type MediaRow={id:string;tenantId:string;propertyId:string;status:string;checksumSha256:string};
type Repo={getProperty(id:string,tenant:string):Promise<PropertyRow|null>;getMedia(ids:string[],tenant:string,property:string):Promise<MediaRow[]>;getOrCreateRun(input:Record<string,unknown>):Promise<{id:string;traceId:string;created:boolean}>};
export type AiMutationResult<T=Record<string,never>>= {ok:true;data:T}|{ok:false;code:"INVALID_INPUT"|"NOT_FOUND"|"VERSION_CONFLICT"|"SERVICE_UNAVAILABLE"|"SUGGESTION_ALREADY_DECIDED"|"RUN_NOT_RETRYABLE"};
export async function startAiIntake(input:unknown,context:Context,repository:Repo,dispatcher:AiJobDispatcher):Promise<AiMutationResult<{runId:string}>>{const p=schema.safeParse(input);if(!p.success)return{ok:false,code:"INVALID_INPUT"};const property=await repository.getProperty(p.data.propertyId,context.tenantId);if(!property)return{ok:false,code:"NOT_FOUND"};if(property.version!==p.data.expectedVersion)return{ok:false,code:"VERSION_CONFLICT"};const media=await repository.getMedia(p.data.mediaIds,context.tenantId,property.id);if(media.length!==p.data.mediaIds.length)return{ok:false,code:"NOT_FOUND"};const snapshot=buildAiInputSnapshot(context,property,media,p.data.agentText);const run=await repository.getOrCreateRun({tenantId:context.tenantId,propertyId:property.id,requesterUserId:context.userId,idempotencyKey:p.data.idempotencyKey,tasks:p.data.tasks,snapshot});try{await dispatcher.enqueue({runId:run.id,tenantId:context.tenantId,traceId:run.traceId,schemaVersion:1});}catch{return{ok:false,code:"SERVICE_UNAVAILABLE"}}return{ok:true,data:{runId:run.id}}}
type DecisionInput={suggestionId:string;expectedPropertyVersion?:number};
export async function decideSuggestion(kind:"accept"|"reject",input:DecisionInput,rpc:(kind:string,input:DecisionInput)=>Promise<unknown>):Promise<AiMutationResult>{try{await rpc(kind,input);return{ok:true,data:{}}}catch(error){const m=error instanceof Error?error.message:"";return{ok:false,code:m.includes("VERSION_CONFLICT")?"VERSION_CONFLICT":m.includes("ALREADY_DECIDED")?"SUGGESTION_ALREADY_DECIDED":"NOT_FOUND"}}}
